# Usa la imagen oficial de Apache como base
FROM httpd:latest

# Copia el contenido de tu sitio al directorio raíz de Apache en el contenedor
COPY www-apache/ /usr/local/apache2/htdocs/

# Exponer el puerto 80 para el servidor web
EXPOSE 80
