# Usa la imagen oficial de Apache como base
FROM nginx:latest

# Copia el contenido de tu sitio al directorio raíz de Apache en el contenedor
COPY www-nginx/ /usr/share/nginx/html/

# Exponer el puerto 80 para el servidor web
EXPOSE 80
